load("//tools/install:install.bzl", "install", "install_files", "install_src_files")

install(
    name = "install",
    deps = [
        "//modules/planning/scenarios/bare_intersection_unprotected:install",
        "//modules/planning/scenarios/emergency_pull_over:install",
        "//modules/planning/scenarios/emergency_stop:install",
        "//modules/planning/scenarios/lane_follow:install",
        "//modules/planning/scenarios/park_and_go:install",
        "//modules/planning/scenarios/pull_over:install",
        "//modules/planning/scenarios/stop_sign_unprotected:install",
        "//modules/planning/scenarios/traffic_light_protected:install",
        "//modules/planning/scenarios/traffic_light_unprotected_left_turn:install",
        "//modules/planning/scenarios/traffic_light_unprotected_right_turn:install",
        "//modules/planning/scenarios/valet_parking:install",
        "//modules/planning/scenarios/yield_sign:install",
        "//modules/planning/scenarios/bare_intersection_unprotected:install_plugin",
        "//modules/planning/scenarios/emergency_pull_over:install_plugin",
        "//modules/planning/scenarios/emergency_stop:install_plugin",
        "//modules/planning/scenarios/lane_follow:install_plugin",
        "//modules/planning/scenarios/park_and_go:install_plugin",
        "//modules/planning/scenarios/pull_over:install_plugin",
        "//modules/planning/scenarios/stop_sign_unprotected:install_plugin",
        "//modules/planning/scenarios/traffic_light_protected:install_plugin",
        "//modules/planning/scenarios/traffic_light_unprotected_left_turn:install_plugin",
        "//modules/planning/scenarios/traffic_light_unprotected_right_turn:install_plugin",
        "//modules/planning/scenarios/valet_parking:install_plugin",
        "//modules/planning/scenarios/yield_sign:install_plugin",
    ],
)

install_src_files(
    name = "install_src",
    deps = [
        "//modules/planning/scenarios/bare_intersection_unprotected:install_src",
        "//modules/planning/scenarios/emergency_pull_over:install_src",
        "//modules/planning/scenarios/emergency_stop:install_src",
        "//modules/planning/scenarios/lane_follow:install_src",
        "//modules/planning/scenarios/park_and_go:install_src",
        "//modules/planning/scenarios/pull_over:install_src",
        "//modules/planning/scenarios/stop_sign_unprotected:install_src",
        "//modules/planning/scenarios/traffic_light_protected:install_src",
        "//modules/planning/scenarios/traffic_light_unprotected_left_turn:install_src",
        "//modules/planning/scenarios/traffic_light_unprotected_right_turn:install_src",
        "//modules/planning/scenarios/valet_parking:install_src",
        "//modules/planning/scenarios/yield_sign:install_src",
    ],
)


