load("//tools/install:install.bzl", "install", "install_files", "install_src_files")

package(default_visibility = ["//visibility:public"])

install(
    name = "install",
    deps = [
        "//modules/planning/traffic_rules/backside_vehicle:install",
        "//modules/planning/traffic_rules/crosswalk:install",
        "//modules/planning/traffic_rules/destination:install",
        "//modules/planning/traffic_rules/keepclear:install",
        "//modules/planning/traffic_rules/reference_line_end:install",
        "//modules/planning/traffic_rules/rerouting:install",
        "//modules/planning/traffic_rules/stop_sign:install",
        "//modules/planning/traffic_rules/traffic_light:install",
        "//modules/planning/traffic_rules/yield_sign:install",
        "//modules/planning/traffic_rules/backside_vehicle:install_plugin",
        "//modules/planning/traffic_rules/crosswalk:install_plugin",
        "//modules/planning/traffic_rules/destination:install_plugin",
        "//modules/planning/traffic_rules/keepclear:install_plugin",
        "//modules/planning/traffic_rules/reference_line_end:install_plugin",
        "//modules/planning/traffic_rules/rerouting:install_plugin",
        "//modules/planning/traffic_rules/stop_sign:install_plugin",
        "//modules/planning/traffic_rules/traffic_light:install_plugin",
        "//modules/planning/traffic_rules/yield_sign:install_plugin",
    ],
)

install_src_files(
    name = "install_src",
    deps = [
        "//modules/planning/traffic_rules/backside_vehicle:install_src",
        "//modules/planning/traffic_rules/crosswalk:install_src",
        "//modules/planning/traffic_rules/destination:install_src",
        "//modules/planning/traffic_rules/keepclear:install_src",
        "//modules/planning/traffic_rules/reference_line_end:install_src",
        "//modules/planning/traffic_rules/rerouting:install_src",
        "//modules/planning/traffic_rules/stop_sign:install_src",
        "//modules/planning/traffic_rules/traffic_light:install_src",
        "//modules/planning/traffic_rules/yield_sign:install_src",
    ],
)


