load("//tools/install:install.bzl", "install", "install_files", "install_src_files")

install(
    name = "install",
    deps = [
        "//modules/external_command/command_processor/action_command_processor:install",
        "//modules/external_command/command_processor/chassis_command_processor:install",
        "//modules/external_command/command_processor/command_processor_base:install",
        "//modules/external_command/command_processor/free_space_command_processor:install",
        "//modules/external_command/command_processor/lane_follow_command_processor:install",
        "//modules/external_command/command_processor/path_follow_command_processor:install",
        "//modules/external_command/command_processor/speed_command_processor:install",
        "//modules/external_command/command_processor/valet_parking_command_processor:install",
        "//modules/external_command/command_processor/action_command_processor:install_plugin",
        "//modules/external_command/command_processor/chassis_command_processor:install_plugin",
        "//modules/external_command/command_processor/free_space_command_processor:install_plugin",
        "//modules/external_command/command_processor/lane_follow_command_processor:install_plugin",
        "//modules/external_command/command_processor/path_follow_command_processor:install_plugin",
        "//modules/external_command/command_processor/speed_command_processor:install_plugin",
        "//modules/external_command/command_processor/valet_parking_command_processor:install_plugin",
    ],
)

install_src_files(
    name = "install_src",
    deps = [
        "//modules/external_command/command_processor/action_command_processor:install_src",
        "//modules/external_command/command_processor/chassis_command_processor:install_src",
        "//modules/external_command/command_processor/command_processor_base:install_src",
        "//modules/external_command/command_processor/free_space_command_processor:install_src",
        "//modules/external_command/command_processor/lane_follow_command_processor:install_src",
        "//modules/external_command/command_processor/path_follow_command_processor:install_src",
        "//modules/external_command/command_processor/speed_command_processor:install_src",
        "//modules/external_command/command_processor/valet_parking_command_processor:install_src",
    ],
)


